### ISSUE TITLE
Sticky Topic - not sticky after edit

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL-4.2.3#128]
> Ein Normaler User erstellt ein Thema.
Er möchte nun das es oben bleibt und bittet mich das Thema hervorzuheben.
Ich setzte das Thema auf sticky, das Thema wird nun hervorgehoben.
...soweit so gut, jetzt kommt der Bug.
Der User bearbeitet nun sein Thema (erster beitrag), danach ist das Thema nicht mehr hervorgehoben!

http://www.webspell.org/index.php?site=forum_topic&topic=43163

**Comment by b1u3** [comment]
83404bf fixes the issue
