### ISSUE TITLE
Replace static icons with Bootstrap Glyphicons where possible

### ISSUE THREAD

**Issue by derchrisuk** [webSPELL/webSPELL-4.2.3#129]
There are still a few opportunities where we could/should replace a static icon with a Bootstrap Glyphicon.

For example asc.gif with chevron-down, 
desc.gif with chevron-up

And so on.

**Comment by blu3bird23** [comment]
glyphicon glyphicon-email does not exists in BS.
glyphicon glyphicon-email should be glyphicon glyphicon-envelope
