### ISSUE TITLE
remove styles module?!

### ISSUE THREAD

**Issue by xxxrenegade** [webSPELL/webSPELL-4.2.3#133]
Ich bin der Meinung das das Syles Module Komplett überflüssig ist.

Homepage Title > Ist schon im Settings Module mit drin.

Page Backgroundcolor, Table Bordercolor, Head-BG, Category-BG, Cell-BG 1, Cell-BG 2, Cell-BG 3, Cell-BG 4 > Sind alles Sachen die nicht mehr gebraucht werden oder halt einmalig vom Anpasser per CSS definiert werden sollte.

Win Fontcolor, Loose Fontcolor, Draw Fontcolor > sollte man jeweils eine CSS Klasse für erstellen.

Bleibt nur noch die Frage ob man das bearbeiten der _stylesheet.css im Backend zulassen sollte oder nicht, wobei ich auch da der Meinung bin das es nicht benötigt wird.

**Comment by Pascalmh** [comment]
This section has become unnecessary - I think you are right, we should get rid of it as it does not make much sense to keep it just to change 3 colors (where it makes sense to keep them in green, orange and red).

**Comment by derchrisuk** [comment]
I veto this.
Not every user of a webSPELL site is confident with HTML/CSS
So they need a way to implement simple style changes from the Admincenter

**Comment by Pascalmh** [comment]
There isn't much for them to change anymore, is there?

**Comment by derchrisuk** [comment]
Well, the commit also removes Cell/Table BG completely from certain files where it is required.

**Comment by xxxrenegade** [comment]
Wo genau bist du gegen? Das man die _stylesheet.css nicht mehr über das Backend bearbeiten kann? Oder das entfernen der Farbverwaltung im Backend, wo die Variablen in den Template Dateien eh nicht mehr vorhanden sind.

**Comment by derchrisuk** [comment]
Just as an example.
You removed the following from `articles.php` L212-L219

`
-        if ($n % 2) {
-            $bg1 = BG_1;
-            $bg2 = BG_2;
-        } else {
-            $bg1 = BG_3;
-            $bg2 = BG_4;
-        }
-
`

We use the style info for BG_? here because we run a modulo on a mysql fetch.
Before we had different Cell BG to format the output,
With this change, there is no more style format.

**Comment by xxxrenegade** [comment]
Das ganze wird in Bootstrap ja jetzt mit .table-striped (   :nth-child()   ) gemacht. Man kann die Farben jetzt halt nur nicht mehr im Backend verwalten, aber ich bin halt auch der Meinung das so was eh nur einmal festgelegt wird und danach nie mehr geändert wird. Bzw. finde ich auch das sowas auch nicht geändert werden soll, der Designer hat sich bei seiner Farbzugsamenstellung schon etwas gedacht, der Kunde würde es dann wieder Kaputt machen.

**Comment by DDaems** [comment]
Can't read german, and my browser only seems to translate the english part.
But as far as i understand, i agree with xxxrenegade.
I think this can be archieved on a little stylesheet with commets explaining what it changes.

And users who have little knowledge will use templates anyway.
I think it should be easyer for webdesigners to change stuff. (it might result in more templates)
And more templates are more users imo.

Now i mostly find myself hacking your bg tags, giving them a random color and overwriting them.
But this approach doesn't 100% work, sinds it will affect more and more different pieces of the website. And sometimes i do not want to change them. Than i need to start hunting that little piece of code down.

Anyway the big bennefit of using a only css approach is easy debugging in the browser with checkboxes. That the inline approach doesn't allow. + More control without needing to hunt a piece of inlinecode. (easyer, less time consuming)

**Comment by Pascalmh** [comment]
> Das ganze wird in Bootstrap ja jetzt mit .table-striped ( :nth-child() ) gemacht.

At the moment it is not done, could you add a commit where you add the proper bs3 classes where you removed the bg1-4

**Comment by xxxrenegade** [comment]
So was fehlt den jetzt noch genau bzw. soll anderes gemacht werden? Steige hier nämlich nicht mehr so ganz durch, liegt vielleicht auch an meinen Englisch Kenntnissen.

Mom geht es ja regelrecht darum das styles Module auszubauen. Das die Templates der Module noch angepasst werden müssen ist klar. Aber das muss ja nicht in diesem Pull geschehen. Sondern wenn man sich um die Anpassung des jeweiligen Modules kümmert.

**Comment by Pascalmh** [comment]
Die Anpassung der Module sollte mit in den PR rein, sonst haben wir nach dem Merge "einen schlechteren Stand als vorher". Wenn du das noch hinzufügst sollten wir es mergen können.

**Comment by xxxrenegade** [comment]
Was genau soll ich den Anpassen bei den Tabellen die .table-striped Klasse setzen oder wie? Bei den meisten Modulen wird ja gar nicht mehr mit einer Tabelle gearbeitet.

**Comment by Pascalmh** [comment]
Einfach schauen wo es Sinn macht noch `table-striped` zu setzen (z.b. Clanwars?) oder wie man es mit dem Kalender nun macht (siehe Kommentar im PR).
