### ISSUE TITLE
Checklogin style (error wrong password etc) should be adapted to BS3

### ISSUE THREAD

**Issue by blu3bird23** [webSPELL/webSPELL-4.2.3#145]
![image](https://cloud.githubusercontent.com/assets/5761799/5693864/5d47fb48-9933-11e4-95fa-00149ffc70d3.png)

**Comment by Pascalmh** [comment]
This is getting fixed here: PR https://github.com/webSPELL/webSPELL-4.2.3/pull/130, Issue https://github.com/webSPELL/webSPELL-4.2.3/issues/119
