### ISSUE TITLE
glyphicon glyphicon-email class

### ISSUE THREAD

**Issue by blu3bird23** [webSPELL/webSPELL-4.2.3#153]
glyphicon glyphicon-email does not exists in BS.
glyphicon glyphicon-email should be glyphicon glyphicon-envelope

**Comment by Pascalmh** [comment]
Can you add this as a Comment to https://github.com/webSPELL/webSPELL-4.2.3/issues/129 so we have everything concerning the Glyphicons in one place? Thank you!
