### ISSUE TITLE
[Insight] Database queries should use parameter binding

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL-4.2.3#166]
**[in comments.php, line 43](https://github.com/webSPELL/webSPELL-4.2.3/blob/265f12fdca099ee8f219a2fc48451adbdd2004e8/comments.php#L43)**

> If provided by the user, the value of `$modul[2]` may allow an SQL injection attack. Avoid concatenating parameters to SQL query strings, and use parameter binding instead.

```php
    $allowed = 0;
    if (array_key_exists($type, $moduls)) {
        $modul = $moduls[ $type ];
        $get = safe_query(
            "SELECT
                " . $modul[ 2 ] . "
            FROM
                " . PREFIX . $modul[ 0 ] . "
            WHERE
                " . $modul[ 1 ] . "='" . (int)$parentID."'"
        );
```

---------------------

**[in rating.php, line 62](https://github.com/webSPELL/webSPELL-4.2.3/blob/265f12fdca099ee8f219a2fc48451adbdd2004e8/rating.php#L62)**

> If provided by the user, the value of `$table` may allow an SQL injection attack. Avoid concatenating parameters to SQL query strings, and use parameter binding instead.

```php
}

if (isset($table) && isset($key)) {
    $getarticles = safe_query(
        "SELECT
            " . $table . "
        FROM
            " . PREFIX . "user
        WHERE
            userID='" . (int)$userID."'"
    );
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/ecedfa24-b238-45fb-9e5e-47850bfb499d/analyses/124?status=violations)_

**Comment by Phhere** [comment]
I do not know how to fix them because there is no user input on these
i think this are false reports

**Comment by Phhere** [comment]
False Report
