### ISSUE TITLE
[Insight] Missing use statement should be avoided

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL-4.2.3#167]
**[in src/func/spam.php, line 183](https://github.com/webSPELL/webSPELL-4.2.3/blob/265f12fdca099ee8f219a2fc48451adbdd2004e8/src/func/spam.php#L183)**

> The `Exception` class resolves to the following classes: `SebastianBergmann\Exporter\Exception` or `SebastianBergmann\GlobalState\Exception` or `Symfony\Component\Config\Definition\Exception\Exception`.
Did you forget to add a corresponding use statement for one of them?

```php
        } elseif (class_exists("HttpRequest")) {
            $request = new \HttpRequest($this->host, \HttpRequest::METH_POST);
            $request->addPostFields($data);
            try {
                return $request->getBody();
            } catch (Exception $ex) {
                $this->logError("No Api-Respone. Code: " . $ex->getCode() . ", Message: " . $ex->getMessage(), $data);
                return "";
            }
        } elseif (ini_get("allow_url_fopen")) {
            $build_data = http_build_query($data);
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/ecedfa24-b238-45fb-9e5e-47850bfb499d/analyses/124?status=violations)_

**Comment by Phhere** [comment]
fixed in 8e1361b51b2ff08e1fe71394fe35ead58050babc
