### ISSUE TITLE
Add hreflang attribute to language switcher

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL-4.2.3#185]
Add the appropriate hreflang Attribute to the language switcher

https://support.google.com/webmasters/answer/189077?hl=en

**Comment by derchrisuk** [comment]
I don't see the benefit in doing this.

**Comment by Pascalmh** [comment]
Seems like we would need a the iso country code somewhere in the URL for it to work. I don't think it is worth the effort.
