### ISSUE TITLE
Better Evals for Templates

### ISSUE THREAD

**Issue by Phhere** [webSPELL/webSPELL-4.2.3#83]
We can reduce the number of codestyle erros by chaning the evals for templates
Old:
```php
eval ("\$logged = \"" . gettemplate("logged") . "\";");
echo $logged;
```
New:
```php
$logged = eval("return \"" . gettemplate("logged") . "\";");
echo $logged;
```

**Comment by Phhere** [comment]
We should rework the template engine to pass an array with all used variables to a function instead of using eval

**Comment by derchrisuk** [comment]
#154
